version: '3.8'

services:
  php:
    image: drupalci/php-7.1-apache:production
    container_name: php_app
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    environment:
      DATABASE_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: test_db
    depends_on:
      - db

  db:
    image: mysql:8.3
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql_db
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    volumes:
      - ./db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
volumes:
  db_data:
